In [20]:
import torch
from torch import nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.utils import shuffle


In [21]:
df=pd.read_csv("/content/Iris.csv")
data = shuffle(df, random_state=42)

In [22]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [23]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [24]:
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [25]:
Species= data["Species"]
target=[]
for m in Species:
    if m == "Iris-setosa":
        target.append(0)
    elif m=="Iris-versicolor":
        target.append(1)
    else:
        target.append(2)

target=torch.tensor(np.array(target))
train_target, test_target= target[0:120],target[120:150]
train_target, test_target= train_target.long(), test_target.long()
test_target.dtype

torch.int64

In [26]:
labels = data.drop(columns=['Species'])
label0=torch.tensor(labels["SepalLengthCm"].to_numpy()).unsqueeze(1).float()
label1=torch.tensor(labels["SepalWidthCm"].to_numpy()).unsqueeze(1).float()
label2=torch.tensor(labels["PetalLengthCm"].to_numpy()).unsqueeze(1).float()
label3=torch.tensor(labels["PetalWidthCm"].to_numpy()).unsqueeze(1).float()
dataset= torch.cat((label1,label2,label3,label3),dim=1)
train_dataset, test_dataset= dataset[0:120], dataset[120:150]
print(train_dataset)
print("----------------------------------------------------")
print(test_dataset)

tensor([[2.8000, 4.7000, 1.2000, 1.2000],
        [3.8000, 1.7000, 0.3000, 0.3000],
        [2.6000, 6.9000, 2.3000, 2.3000],
        [2.9000, 4.5000, 1.5000, 1.5000],
        [2.8000, 4.8000, 1.4000, 1.4000],
        [3.4000, 1.5000, 0.4000, 0.4000],
        [2.9000, 3.6000, 1.3000, 1.3000],
        [3.1000, 5.1000, 2.3000, 2.3000],
        [2.2000, 4.5000, 1.5000, 1.5000],
        [2.7000, 3.9000, 1.2000, 1.2000],
        [3.2000, 5.1000, 2.0000, 2.0000],
        [3.0000, 1.4000, 0.1000, 0.1000],
        [3.5000, 1.3000, 0.2000, 0.2000],
        [3.1000, 1.5000, 0.1000, 0.1000],
        [3.8000, 1.5000, 0.3000, 0.3000],
        [3.3000, 4.7000, 1.6000, 1.6000],
        [3.0000, 5.8000, 2.2000, 2.2000],
        [2.5000, 3.9000, 1.1000, 1.1000],
        [2.8000, 4.5000, 1.3000, 1.3000],
        [2.8000, 5.6000, 2.2000, 2.2000],
        [3.2000, 1.6000, 0.2000, 0.2000],
        [3.0000, 4.9000, 1.8000, 1.8000],
        [3.4000, 1.6000, 0.4000, 0.4000],
        [2.8000, 5.6000, 2.1000, 2

In [27]:
print(test_dataset.dtype)

torch.float32


In [28]:
device= torch.device("cuda" if torch.cuda.is_available() else "cpu")
train_dataset, test_dataset= train_dataset.to(device), test_dataset.to(device)
test_dataset.device, train_dataset.device

(device(type='cpu'), device(type='cpu'))

In [29]:
train_target.to(device), test_target.to(device)

(tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
         2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2,
         1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0,
         2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
         0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 1]),
 tensor([1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2,
         0, 1, 2, 0, 1, 2]))

In [30]:
train_target.shape

torch.Size([120])

In [31]:
test_dataset.size()

torch.Size([30, 4])

In [32]:
class IrisModel(nn.Module):
  def __init__(self, in_features: int, hidden_units: int, out_features: int):
    super().__init__()
    self.layer_stack = nn.Sequential(
        nn.Linear(in_features=in_features, out_features=hidden_units),
        nn.Linear(in_features=hidden_units, out_features=hidden_units),
        nn.Linear(in_features=hidden_units, out_features=out_features),
    )


  def forward(self,x):
    return self.layer_stack(x)

In [33]:
torch.manual_seed(42)
model0= IrisModel(4,10,3).to(device)
next(model0.parameters())

Parameter containing:
tensor([[ 0.3823,  0.4150, -0.1171,  0.4593],
        [-0.1096,  0.1009, -0.2434,  0.2936],
        [ 0.4408, -0.3668,  0.4346,  0.0936],
        [ 0.3694,  0.0677,  0.2411, -0.0706],
        [ 0.3854,  0.0739, -0.2334,  0.1274],
        [-0.2304, -0.0586, -0.2031,  0.3317],
        [-0.3947, -0.2305, -0.1412, -0.3006],
        [ 0.0472, -0.4938,  0.4516, -0.4247],
        [ 0.3860,  0.0832, -0.1624,  0.3090],
        [ 0.0779,  0.4040,  0.0547, -0.1577]], requires_grad=True)

In [34]:
import requests
request = requests.get("https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/helper_functions.py")
with open("helper_functions.py", "wb") as f:
  f.write(request.content)

from helper_functions import accuracy_fn

In [35]:
lossFn= nn.CrossEntropyLoss()
optimizer= torch.optim.SGD(model0.parameters(), lr=0.01)

torch.manual_seed(42)
epochs= 750

for epoch in range(epochs):
    model0.train()
    train_pred=model0(train_dataset)
    train_loss=lossFn(train_pred,train_target)
    optimizer.zero_grad()
    train_loss.backward()
    optimizer.step()

    with torch.inference_mode():
        model0.eval()
        test_pred=model0(test_dataset)
        test_loss=lossFn(test_pred,test_target)
        acc= accuracy_fn(test_pred.argmax(dim=1),test_target)

    if epoch%20==0:
        print(f"{epoch}.epoch>>> train loss:{train_loss:.4f}----test loss:{test_loss:.4f}----{acc:.2f}%")



0.epoch>>> train loss:1.3534----test loss:1.3858----36.67%
20.epoch>>> train loss:1.0414----test loss:1.0398----40.00%
40.epoch>>> train loss:0.9754----test loss:0.9666----50.00%
60.epoch>>> train loss:0.9141----test loss:0.9123----63.33%
80.epoch>>> train loss:0.8458----test loss:0.8562----63.33%
100.epoch>>> train loss:0.7729----test loss:0.7970----63.33%
120.epoch>>> train loss:0.7018----test loss:0.7384----63.33%
140.epoch>>> train loss:0.6383----test loss:0.6848----63.33%
160.epoch>>> train loss:0.5855----test loss:0.6392----63.33%
180.epoch>>> train loss:0.5432----test loss:0.6014----63.33%
200.epoch>>> train loss:0.5095----test loss:0.5703----63.33%
220.epoch>>> train loss:0.4821----test loss:0.5442----70.00%
240.epoch>>> train loss:0.4594----test loss:0.5218----80.00%
260.epoch>>> train loss:0.4399----test loss:0.5018----83.33%
280.epoch>>> train loss:0.4226----test loss:0.4837----90.00%
300.epoch>>> train loss:0.4070----test loss:0.4667----90.00%
320.epoch>>> train loss:0.3925